jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_USER}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Administer:admin"
        - "GROUP:Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://localhost:8080/
appearance:
  themeManager:
    disableUserThemes: true
    theme: "dark"
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "xoa_user"
              secret: "${XOA_USER}"
              description: "Secret Text"
          - string:
              scope: GLOBAL
              id: "xoa_password"
              secret: "${XOA_PASSWORD}"
              description: "Secret Text"
          - string:
              scope: GLOBAL
              id: "aws_access_key_id"
              secret: "${AWS_ACCESS_KEY_ID}"
              description: "Secret Text"
          - string:
              scope: GLOBAL
              id: "aws_secret_access_key"
              secret: "${AWS_SECRET_ACCESS_KEY}"
              description: "Secret Text"
          - string:
              scope: GLOBAL
              id: "jenkins-pub-key"
              secret: "${readFile:/certs/id_ed25519.pub}"
              description: "SSH public key file."
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "jenkins-priv-key"
              username: ""
              passphrase: ""
              description: "SSH private key file"
              privateKeySource:
                directEntry:
                  privateKey: "${SSH_PRIVATE_KEY}}" 
jobs:
  # - script: >
  #     folder('Kubernetes-IaC')
  - script: >
      # pipelineJob('Kubernetes-IaC/Cluster-Xen-Orchestra') {
      pipelineJob('test') {
        definition {
            cpsScm {
                scm {
                    git {
                        remote {
                            url('https://github.com/rodrigo-zvd/homelab.git')
                            // Para repositórios privados, adicione:
                            // credentials('seu-id-de-credencial')
                        }
                        branch('*/main')
                    }
                }
                scriptPath('Jenkinsfile')
            }
        }
      }