# Base Jenkins image
FROM ronivay/xen-orchestra:latest

# Switch to root to install dependencies
USER root

RUN npm install --global xo-cli

RUN xo-cli register --allowUnauthorized http://localhost admin@admin.net admin
RUN xo-cli server.add host=192.168.1.102 username="root" password="m3gaFox50" autoConnect=true allowUnauthorized=true