pipeline {
  agent any

  environment {
    XOA_USER = credentials('xoa_user')
    XOA_PASSWORD = credentials('xoa_password')
    AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
    AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    JENKINS_PUB_KEY = credentials('jenkins-pub-key')
  }
  
  parameters {
    choice(
      name: 'CREATE_OR_DESTROY',
      choices: ['Create', 'Destroy'],
      description: 'Would you like to create or destroy the Kubernetes cluster?'
    )
    booleanParam(
      name: 'DEBUG',
      defaultValue: false,
      description: 'Se ativado, exporta os valores das credenciais como artefatos para depuração'
    )
  }

  stages {

    stage('Exportar credenciais para artefatos') {
      when {
        expression { return params.DEBUG }
      }
      steps {
        withCredentials([
          string(credentialsId: 'xoa_user', variable: 'REAL_XOA_USER'),
          string(credentialsId: 'xoa_password', variable: 'REAL_XOA_PASSWORD'),
          string(credentialsId: 'aws_access_key_id', variable: 'REAL_AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws_secret_access_key', variable: 'REAL_AWS_SECRET_ACCESS_KEY'),
          string(credentialsId: 'jenkins-pub-key', variable: 'REAL_JENKINS_PUB_KEY'),
        ]) {
          sh '''
            echo "$REAL_XOA_USER" > xoa_user.txt
            echo "$REAL_XOA_PASSWORD" > xoa_password.txt
            echo "$REAL_AWS_ACCESS_KEY_ID" > aws_access_key_id.txt
            echo "$REAL_AWS_SECRET_ACCESS_KEY" > aws_secret_access_key.txt
            echo "$REAL_JENKINS_PUB_KEY" > jenkins_pub_key.txt
          '''
        }

        archiveArtifacts artifacts: 'xoa_user.txt', onlyIfSuccessful: true
        archiveArtifacts artifacts: 'xoa_password.txt', onlyIfSuccessful: true
        archiveArtifacts artifacts: 'aws_access_key_id.txt', onlyIfSuccessful: true
        archiveArtifacts artifacts: 'aws_secret_access_key.txt', onlyIfSuccessful: true
        archiveArtifacts artifacts: 'jenkins_pub_key.txt', onlyIfSuccessful: true
      }
    }
    
    stage('authentication') {
      agent {
        docker {
          image 'alpine'
        }
      }
      steps {
        dir('terraform') {
          withCredentials([
            sshUserPrivateKey(credentialsId: 'jenkins-priv-key', keyFileVariable: 'JENKINS_PRIV_KEY')
            ]) {
            sh '''
              cp "$JENKINS_PRIV_KEY" id_ed25519
              echo "$JENKINS_PUB_KEY" > id_ed25519.pub
            '''
            }
        }
      }
    }

//     stage('setup terraform endpoints') {
//       steps {
//         script {
//           def minioIp = sh(script: "getent hosts minio | awk '{ print \$1 }'", returnStdout: true).trim()
//           env.MINIO_URL = minioIp
//           def xoaIp = sh(script: "getent hosts xen-orchestra | awk '{ print \$1 }'", returnStdout: true).trim()
//           env.XOA_IP = xoaIp
//         }
//       }
//     }
  
//     stage('init') {
//       agent {
//         docker {
//           image 'hashicorp/terraform:1.11.4'
//           args "--entrypoint= --add-host minio:${env.MINIO_URL} --add-host xen-orchestra:${env.XOA_IP}"
//         }
//       }
//       steps {
//         dir('terraform'){
//         sh '''
//           terraform init -no-color
//         '''
//         }
//       }
//     }
  
//     stage('plan') {
//       agent {
//         docker {
//           image 'hashicorp/terraform:1.11.4'
//           args "--entrypoint= --add-host minio:${env.MINIO_URL} --add-host xen-orchestra:${env.XOA_IP}"
//         }
//       }
//       steps {
//         dir('terraform'){
//         sh '''
//           terraform plan -no-color
//         '''
//         }
//       }
//       when {
//         expression {
//           params.CREATE_OR_DESTROY == "Create"
//         }
//       }
//     }

//     stage('apply') {
//       agent {
//         docker {
//           image 'hashicorp/terraform:1.11.4'
//           args "--entrypoint= --add-host minio:${env.MINIO_URL} --add-host xen-orchestra:${env.XOA_IP}"
//         }
//       }
//       steps {
//         dir('terraform'){
//         sh '''
//           terraform apply -no-color -auto-approve
//         '''
//         }
//       }
//       when {
//         expression {
//           params.CREATE_OR_DESTROY == "Create"
//         }
//       }
//     }

//     // stage('kubespray') {
//     //   agent {
//     //     docker {
//     //       image 'quay.io/kubespray/kubespray:v2.26.0'
//     //       args '--entrypoint="" -u root'
//     //     }
//     //   }
//     //   steps {
//     //     dir('terraform') {
//     //       sh '''
//     //         export ANSIBLE_ROLES_PATH="$ANSIBLE_ROLES_PATH:/kubespray/roles"
//     //         export ANSIBLE_HOST_KEY_CHECKING="False"

//     //         ansible-playbook \
//     //           --become \
//     //           --inventory inventory.ini \
//     //           --extra-vars "kube_network_plugin=flannel" \
//     //           --private-key id_ed25519 \
//     //           /kubespray/cluster.yml
//     //       '''
//     //     }
//     //   }
//     //   when {
//     //     expression {
//     //       params.CREATE_OR_DESTROY == "Create"
//     //     }
//     //   }
//     // }

//     stage('destroy') {
//       agent {
//         docker {
//           image 'hashicorp/terraform:1.11.4'
//           args "--entrypoint= --add-host minio:${env.MINIO_URL} --add-host xen-orchestra:${env.XOA_IP}"
//         }
//       }
//       steps {
//         dir('terraform') {
//           sh '''
//             terraform apply -destroy -no-color -auto-approve
//           '''
//         }
//       }
//       when {
//         expression {
//           params.CREATE_OR_DESTROY == "Destroy"
//         }
//       }
//     }

}
} 