pipeline {
  agent any
  environment {
    XOA_URL = credentials('xoa_url')
    XOA_USER = credentials('xoa_user')
    XOA_PASSWORD = credentials('xoa_password')
    AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
    AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    // MINIO_URL = 
  }
  stages {
    stage('Capturar IP do MinIO') {
      steps {
        script {
          def minioIp = sh(script: "getent hosts minio | awk '{ print \$1 }'", returnStdout: true).trim()
          env.MINIO_URL = minioIp
        }
      }
    }
    stage('Usar MINIO_URL') {
      steps {
        echo "IP do MinIO: ${env.MINIO_URL}"
      }
    }
    stage('init') {
      agent {
        docker {
          image 'hashicorp/terraform:1.11.4'
          args "--entrypoint= --add-host minio:${env.MINIO_URL}"
        }
      }
      steps {
        dir('terraform'){
        sh '''
          terraform init -no-color
          sleep 3600
        '''
        }
      }
    }
  }
}